In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


import io
import base64
from IPython.display import HTML


<table><tr>
    <td>
    <h1>  What is </h1>
    </td>
    <td>
    ![python_logo](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)    
    </td>
    <td>
    <h1>  ? </h1>
    </td>
    
</tr></table>

<table>
  <col width="300">
  <col width="40">
    <tr>
    <td>       
    ![python_logo](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)    
    </td>
    
    <td>
    <h2>is</h2>
    </td>
    
    <td><font size="+2">
    <ul>
    <li>modern</li> 
    <li>general-purpose</li>
    <li>object-oriented</li>
    <li>high-level</li> 
    <li>open source</li> 
    </ul>
    </font></td>
    <td><td><font>
    <h2>programming language</h2>
    </font></td>
</tr></table> 


In [ ]:
video = io.open('Programming_Languages.mp4', 'r+b').read()
encoded = base64.b64encode(video)
HTML(data='''<video alt="test" width="90%" controls>
<source src="data:video/mp4;base64,{0}" type="video/mp4" />
</video>'''.format(encoded.decode('ascii'))
)

## General characteristics of Python.

* **clean and simple language**:  
Easy-to-read and intuitive code, easy-to-learn minimalistic syntax, maintainability scales well with size of projects.

* **dynamically typed**:  
No need to define the type of variables, function arguments or return types.

* **interpreted**:  
No need to compile the code. The Python interpreter reads and executes the python
code directly.

## Google
Google has been a supporter of Python from nearly the very beginning. In the beginning, the founders of Google made the decision of “Python where we can, C++ where we must.”

## Facebook
Facebook production engineers are exceptionally keen on Python, making it the third most popular language at the social media giant

## Instagram
In 2016, the Instagram engineering team boasted that they were running the world’s largest deployment of the Django web framework, which is written entirely in Python. 


## Spotify
This music streaming giant is a huge proponent of Python, using the language primarily for data analysis and back end services.

## Dropbox
This cloud based storage system uses Python in its desktop client. If you have any doubt at all about how invested Dropbox is in Python, consider that in 2012, they managed to convince Guido van Rossum, Python’s creator and benevolent dictator for life, away from Google and into the Dropbox fold

## Netflix
Netflix uses Python for everything from operations management and analysis through to security and networking. In their blogpost, they wrote, “We use Python through the full content lifecycle, from deciding which content to fund all the way to operating the CDN that serves the final video to 148 million members.


## Microsoft

Just eight years ago, Python's footprint within Microsoft was a few scattered engineers who cared about the open source language, with most of the company giving it shrug.

Today, Python is "one of the essential languages for services and teams to support, as well as the most popular choice for the rapidly growing field of data science and analytics both inside and outside of the company," a Microsoft engineer wrote 

Microsoft is the world's biggest open source contributor, at least, as measured by the number of employees actively contributing to open source projects on GitHub. In fact, Microsoft has double the number of open source contributors as the second most active contributor

<table> 
  <col width="300">
  <col width="430">
    <tr>
    <td>       
    ![black_hole](black-hole.jpg)    
    </td>
    
    <td>
    ![chirp](gw.jpg)
    </td>


</tr></table>  



In [ ]:
1+1


In [ ]:
print(*dir(1))


<center>
![python_interp](py_interpreter.png)
</center>

In [ ]:
import dis

def plus(x,y):
    f=x+y
    return f
    

dis.dis(plus)


<table><tr>
    <td><img src="Jupyter_logo.png" width ="300" height="300" /> </td>
    <td>
        <font size="+2">
        <h2>Jupyter Notebook</h2>
        <br>        
        An open-source web application to create documents containing
        <br>       
        <ul>
        <li>live code </li> 
        <li> equations</li> 
        <li> visualizations</li> 
        <li> text</li>
        </ul>
        </font>
    </td>
</tr></table>

In [ ]:
α = 4.5
γ = 0.01
θ = 45

print( α + γ + θ)

### Markdown - Text in the cells  

This is *rich* **text** with [links](http://ipython.org),
equations:
$$\hat{f}(\xi) = \int_{-\infty}^{+\infty} f(x)\,
 \mathrm{e}^{-i \xi x}$$
code with syntax highlighting:
```python
print("Hello world!")
``` 

In [ ]:
from IPython.display import Image

Image(  url=  'http://www.theiapm.ie/templates/rt_mediamogul_j15/images/style5/logo.png')


In [ ]:
%%timeit

y = plus(1,1)

In [ ]:
%%latex
\begin{aligned}
\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} & = \frac{4\pi}{c}\vec{\mathbf{j}} \\
\nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\
\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\
\nabla \cdot \vec{\mathbf{B}} & = 0
\end{aligned}

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
fig, ax = plt.subplots(figsize=(12,6))

Av=np.array([99.6,97.5,98.3,88.5,98.2,99.3,85.6,97.2,100,96,99.1,97])
Lf=np.array([98.2,99.8,99.8,95.9,95.8,99.8,98.7,98.3,97.5,97.7,96.1,97])
Gc=np.array([99.7,99.7,100,97.2,90.8,96,94.3,97.5,100,97.5,94.5,97])
Dd=np.array([99.8,99.7,99.7,96.9,98.6,99.3,91.7,92.6,95.6,97.5,99.7,97])

Xnum=np.arange(13)
Xax=["Mar","Apr","May","June","July","Aug","Sept","Oct","Nov","Dec","Jan","Feb","Avg"]
Av=np.append(Av,Av[-12:].mean())
Lf=np.append(Lf,Lf[-12:].mean())
Gc=np.append(Gc,Gc[-12:].mean())
Dd=np.append(Dd,Dd[-12:].mean())


ax.plot(Xnum,Av, 'D',ls='None', ms=10,markerfacecolor="yellow", markeredgewidth=2, markeredgecolor="blue" ,label="Avoca")
ax.plot(12,Av[-1], 'D',ls='None', ms=15,markerfacecolor="yellow", markeredgewidth=2, markeredgecolor="blue" )
ax.plot(Xnum,Lf, 'o', ms=8, lw=2,  mfc='blue',markeredgewidth=2,markeredgecolor="yellow",label="Liffey")
ax.plot(12,Lf[-1], 'o', ms=12, lw=2,  mfc='blue',markeredgewidth=2,markeredgecolor="yellow")
ax.plot(Xnum,Gc, 's', ms=10, lw=2,  mfc='green',label="Grand Canal")
ax.plot(12,Gc[-1], 's', ms=15, lw=2,  mfc='green')
ax.plot(Xnum,Dd, 's', ms=10, lw=2,  mfc='violet',label="Dodder")
ax.plot(12,Dd[-1], 's', ms=15, lw=2,  mfc='violet')
ax.legend(loc=0,numpoints=1) # let matplotlib decide the optimal location
ax.grid()
ax.set_xticks(np.arange(14))
ax.set_xticklabels(Xax);
fig.savefig('graph1.png')


![mygraph](graph1.png)

![pdf_before](pdf_fdp.png)

In [ ]:
import PyPDF2
 
pdf_in = open(r'commissioning_book.pdf', 'rb')
pdf_reader = PyPDF2.PdfFileReader(pdf_in)
pdf_writer = PyPDF2.PdfFileWriter()
 
for pagenum in range(pdf_reader.numPages):
    page = pdf_reader.getPage(pagenum)
    if pagenum in range(1,pdf_reader.numPages,2):
        page.rotateClockwise(180)
    pdf_writer.addPage(page)
 
pdf_out = open('rotated.pdf', 'wb')
pdf_writer.write(pdf_out)
pdf_out.close()
pdf_in.close()

![pdf_after](pdf_pdf.png)

In [ ]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

url = 'http://www.met.ie/latest/reports.asp'

soup = BeautifulSoup(urlopen(url).read(), "lxml") #markup_type=markup_type))

#soup = BeautifulSoup(urlopen(url).read())

Ptime = soup.findAll('section')[1].findAll('h2')[0].contents[0][23:]
site = soup.findAll('tr')[8].findAll('th')[0].contents[0]
DA_press=float(soup.findAll('tr')[8].findAll('td')[7].contents[0].encode('utf-8'))

SJH_press = round(DA_press* (1 - (2.25577* 10**-5)* 22)**5.25588,1)
BH_press = round(DA_press* (1 - (2.25577* 10**-5)* 45)**5.25588,1)
SLH_press = round(DA_press* (1 - (2.25577* 10**-5)* 35)**5.25588,1)


print( Ptime + "\npressure is %.1f hPa at SJH, %.1f hPa at BH, %.1f hPa at SLR" %(SJH_press, BH_press, SLH_press) )

In [ ]:
Image('Capture121015.JPG')

In [ ]:
ϵ, A, a, B, b = 0.5, 0.1194, 0.104, 0.1037, 0.3158

def kernel(r,θ):
    if r == 0:
        return 0
    vary_theta = (1-ϵ)/(1 - ϵ*np.cos(θ))
    vary_radius = (A*np.exp(-a*r)-B*np.exp(-b*r))/r**2
    return vary_theta*vary_radius

vernel = np.vectorize(kernel)

cube_radius = np.ones((300,100,100))
cube_theta = np.ones((300,100,100))

for i in np.arange(300):
    if i==150:
        h=0.001
    else:
        h=0
    for j in np.arange(100):
        for k in np.arange(100):
            cube_theta[i,j,k] = np.arctan( np.sqrt(((j-50)/5)**2 +((k-50)/5)**2)/
                                          ((i+h-150)/5) ) 
cube_theta[:150,:,:] += np.pi

for i in np.arange(300):
    for j in np.arange(100):
        for k in np.arange(100):
            cube_radius[i,j,k] = np.sqrt(((i-150)/5)**2 +
                                         ((j-50)/5)**2 +
                                         ((k-50)/5)**2)  
                        
dose_kernel = vernel(cube_radius,cube_theta)
np.save("dose_kernel", dose_kernel)

In [ ]:
dose_kernel = np.load("dose_kernel"+'.npy')
#the 10cm cubic block of water
block = np.zeros((100,100,100))
#the incident beam with no absorption
block[:,50,50] = np.ones((100,))
#the incident beam with a guess at the absorption coefficient.
for i in np.arange(100):
    block[i] *= np.exp(-0.02*i)

pencil = np.zeros((100,100,100))
for i in np.arange(100):
    # the roll_zeropad function is defined later in the notebook.
    qaz = roll_zeropad(dose_kernel,-150+i, axis = 0)[:100,:,:]
    pencil += qaz*block[i,50,50]

pen_primary = np.ones((100,))
for i in np.arange(100):
    pen_primary[i] *= np.exp(-0.02*i)
    
    

In [ ]:
from scipy.signal import convolve2d

block[:,25:75,25:75] = np.ones((100,50,50))
ssd = 500
for i in np.arange(1,100):
    block[i] = clipped_zoom(block[0],(500+i*2)/500)
for i in np.arange(100):
    block[i] *= np.exp(-0.02*i)
    
scatter = np.zeros((100,100,100))
for i in np.arange(100):
    scatter[i] = convolve2d(block[i], pencil[i], mode = 'same')

np.save("scatter", scatter)
np.save("block", block)

In [ ]:
scatter = np.load("scatter"+'.npy')
block = np.load("block"+'.npy')
plt.figure(figsize=(8,8))
slice=scatter[:,50,:]+100*block[:,50,:]
vx = plt.contour(np.rot90(slice,3),linewidths =2,colors='w')
plt.imshow(np.rot90(slice,3))


In [ ]:
for cc in vx.collections:
    
    if len(cc.get_paths()) >0:
        p = cc.get_paths()[0]
        v = p.vertices
        x = v[:,0]
        y = v[:,1]

        plt.plot(x,y)            


In [ ]:
Image('Capture221015.JPG',width=1000,height=400)

In [ ]:
Image('kV_MU.JPG',width=600,height=600)

https://pmccavana.github.io

In [ ]:
!pip install fortran-magic

In [ ]:
%load_ext fortranmagic

In [ ]:
%%fortran

subroutine f1(x, y, z)
    real, intent(in) :: x,y
    real, intent(out) :: z

    z = sin(x+y)

end subroutine f1


In [ ]:
f1(np.pi/3,np.pi/4)

In [ ]:
from uncertainties import ufloat
import uncertainties as u
from uncertainties import unumpy

uncertainty = 1.5*np.random.rand(21)
y_error = 10*np.random.rand(21)
n = 1

# Define x and y
x = np.arange(21)+np.random.rand()*3
# Take power of x values according to n
x_pow = x ** n
x_uncertainty =  uncertainty

# np.c_ is an array version of zip
x_fit = unumpy.uarray(np.c_[x_pow, np.ones_like(x)],
                      np.c_[x_uncertainty, np.zeros_like(x_uncertainty)])

y = np.arange(0,101,5)++np.random.rand()*5
y_fit = unumpy.uarray(y, y_error)


In [ ]:
import seaborn as sns
plt.style.use('seaborn-darkgrid')
plt.errorbar(x_pow,y,yerr=y_error,xerr=x_uncertainty,fmt='bo',ecolor='r')

$$
( X^{T}X ) \hat{\beta} = X^{T}y
$$

\begin{equation}
X = \begin{bmatrix}
    x_1 & 1 \\
    x_2 & 1 \\ 
    \vdots & \vdots \\ 
    x_n & 1 \\
    \end{bmatrix} 
\end{equation}

and 

\begin{equation}
\hat{\beta} = \begin{bmatrix}
    a \\
    b \\ 
    \end{bmatrix}
\end{equation}    

In [ ]:
# Use normal equations to find coefficients
inv_mat = unumpy.ulinalg.pinv(x_fit.T.dot(x_fit))
fit_a, fit_b = inv_mat.dot(x_fit.T.dot(y_fit))

print('fit_a={}, fit_b={}'.format(fit_a, fit_b))

In [ ]:
import pandas as pd

df = pd.read_excel('fruit_sales.xlsx', header=None)
df

In [ ]:
import zipfile

document = zipfile.ZipFile('file-sample_500kB.docx')
document.namelist()

In [ ]:

try:
    from xml.etree.cElementTree import XML
except ImportError:
    from xml.etree.ElementTree import XML

xml_content = document.read('word/document.xml')
document.close()
tree = XML(xml_content)



In [ ]:
WORD_NAMESPACE = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
PARA = WORD_NAMESPACE + 'p'
TEXT = WORD_NAMESPACE + 't'

paragraphs = []
for paragraph in tree.getiterator(PARA):
    texts = [node.text
             for node in paragraph.getiterator(TEXT)
             if node.text]
    if texts:
        paragraphs.append(''.join(texts))

'\n\n'.join(paragraphs)

In [ ]:
from pymc3 import  *
plt.style.use('seaborn-darkgrid')

drug = (101,100,102,104,102,97,105,105,98,101,100,123,105,103,100,95,102,106,
        109,102,82,102,100,102,102,101,102,102,103,103,97,97,103,101,97,104,
        96,103,124,101,101,100,101,101,104,100,101)
placebo = (99,101,100,101,102,100,97,101,104,101,102,102,100,105,88,101,100,
           104,100,100,100,101,102,103,97,101,101,100,101,99,101,100,100,
           101,100,99,101,100,102,99,100,99)

y1 = np.array(drug)
y2 = np.array(placebo)
y = pd.DataFrame(dict(value=np.r_[y1, y2], group=np.r_[['drug']*len(drug), ['placebo']*len(placebo)]))

y.hist('value', by='group', figsize=(12, 4));

In [ ]:
μ_m = y.value.mean()
μ_s = y.value.std() * 2

with Model() as model:
    group1_mean = Normal('group1_mean', mu=μ_m, sd=μ_s)
    group2_mean = Normal('group2_mean', mu=μ_m, sd=μ_s)

In [ ]:
σ_low = 0.5
σ_high = 10

with model:
    group1_std = Uniform('group1_std', lower=σ_low, upper=σ_high)
    group2_std = Uniform('group2_std', lower=σ_low, upper=σ_high)

In [ ]:
with model:
    ν = Exponential('ν', 1/30) 


In [ ]:
with model:
    λ1 = group1_std**-2
    λ2 = group2_std**-2

    group1 = StudentT('drug', nu=ν, mu=group1_mean, lam=λ1, observed=y1)
    group2 = StudentT('placebo', nu=ν, mu=group2_mean, lam=λ2, observed=y2)

In [ ]:
with model:
    diff_of_means = Deterministic('difference of means', group1_mean - group2_mean)
    diff_of_stds = Deterministic('difference of stds', group1_std - group2_std)
    effect_size = Deterministic('effect size',
                                   diff_of_means / np.sqrt((group1_std**2 + group2_std**2) / 2))

In [ ]:
with model:
    trace = sample(2000)

In [ ]:
plot_posterior(trace, var_names=['group1_mean','group2_mean', 'group1_std', 'group2_std', 'ν'], figsize =(10,6));

In [ ]:
plot_posterior(trace, var_names=['difference of means','difference of stds', 'effect size'], ref_val=0, figsize =(10,4));

In [ ]:
traceplot(trace[1000:]);

In [ ]:
from scipy.stats import t

plt.figure(figsize=(12,8))
plt.hist(drug, alpha =0.5)
ex= np.arange(75,130,0.2)
for i in np.arange(0,2000,100):  
    tee = t.pdf(ex, trace[i]['ν'], trace[i]['group1_mean'], trace[i]['group1_std'])
    tee /= tee.sum()
    plt.plot(ex,tee*750)

In [ ]:
import pydicom

ds=pydicom.read_file('151321_RTFinalReduceMandible-QA1.DCM',force=True)

In [ ]:
beam=ds.BeamSequence[0]

allMLCs=np.zeros((len(beam.ControlPointSequence),80))
allYjaws=np.zeros((len(beam.ControlPointSequence),2))
seqs = []
for i in np.arange(len(beam.ControlPointSequence)):
    seqs.append([])

for i in np.arange(len(beam.ControlPointSequence)):
    seqs[i] = beam.ControlPointSequence[i]
    allMLCs[i,:] = beam.ControlPointSequence[i].BeamLimitingDevicePositionSequence[2].LeafJawPositions 
    allYjaws[i,:] = beam.ControlPointSequence[i].BeamLimitingDevicePositionSequence[1].LeafJawPositions
    

In [ ]:
from time import sleep
from IPython.display import clear_output

for j in np.arange(0,200,4):
    plt.figure(figsize=(12,8))
    plt.step(np.arange(41),np.r_[allMLCs[j][0],allMLCs[j][:40]])
    plt.step(np.arange(41),np.r_[allMLCs[j][40],allMLCs[j][40:]])
    plt.ylim((-100,100))
    plt.show()
    sleep(0.1)
    clear_output(wait=True)

In [ ]:
from skimage.data import hubble_deep_field

plt.imshow(hubble_deep_field())

In [ ]:
from scipy.ndimage import label

image = (hubble_deep_field()[:,:,0] > 120)


labels, num_features = label(image)
'''
the kernel for attachment
[[0,1,0],
 [1,1,1],
 [0,1,0]]
'''

print("Image contains {} objects".format(num_features))
plt.imshow(labels,cmap='rainbow');

In [ ]:
labels[840:860,597:607]

<table>
  <col width="600">
  <col width="400">
    <tr>
    <td>       
    ![python_logo](https://www.ibm.com/quantum-computing/_nuxt/img/12337e2.jpg)    
    </td>
    
    <td>
    <h2>IBM Q Experience is quantum on the cloud</h2>
    </td>
</tr></table> 


In [ ]:
import numpy as np
from qiskit import *
%matplotlib inline

![b](Unknown.png)
![b](Unknown-2.png)

![c](Unknown-3.png)

![d](Unknown-4.png)

In [ ]:
def roll_zeropad(a, shift, axis=None):
    """
    Roll array elements along a given axis.

    Elements off the end of the array are treated as zeros.

    Parameters
    ----------
    a : array_like
        Input array.
    shift : int
        The number of places by which elements are shifted.
    axis : int, optional
        The axis along which elements are shifted.  By default, the array
        is flattened before shifting, after which the original
        shape is restored.

    Returns
    -------
    res : ndarray
        Output array, with the same shape as `a`.

    See Also
    --------
    roll     : Elements that roll off one end come back on the other.
    rollaxis : Roll the specified axis backwards, until it lies in a
               given position.

    Examples
    --------
    >>> x = np.arange(10)
    >>> roll_zeropad(x, 2)
    array([0, 0, 0, 1, 2, 3, 4, 5, 6, 7])
    >>> roll_zeropad(x, -2)
    array([2, 3, 4, 5, 6, 7, 8, 9, 0, 0])

    >>> x2 = np.reshape(x, (2,5))
    >>> x2
    array([[0, 1, 2, 3, 4],
           [5, 6, 7, 8, 9]])
    >>> roll_zeropad(x2, 1)
    array([[0, 0, 1, 2, 3],
           [4, 5, 6, 7, 8]])
    >>> roll_zeropad(x2, -2)
    array([[2, 3, 4, 5, 6],
           [7, 8, 9, 0, 0]])
    >>> roll_zeropad(x2, 1, axis=0)
    array([[0, 0, 0, 0, 0],
           [0, 1, 2, 3, 4]])
    >>> roll_zeropad(x2, -1, axis=0)
    array([[5, 6, 7, 8, 9],
           [0, 0, 0, 0, 0]])
    >>> roll_zeropad(x2, 1, axis=1)
    array([[0, 0, 1, 2, 3],
           [0, 5, 6, 7, 8]])
    >>> roll_zeropad(x2, -2, axis=1)
    array([[2, 3, 4, 0, 0],
           [7, 8, 9, 0, 0]])

    >>> roll_zeropad(x2, 50)
    array([[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]])
    >>> roll_zeropad(x2, -50)
    array([[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]])
    >>> roll_zeropad(x2, 0)
    array([[0, 1, 2, 3, 4],
           [5, 6, 7, 8, 9]])

    """
    a = np.asanyarray(a)
    if shift == 0: return a
    if axis is None:
        n = a.size
        reshape = True
    else:
        n = a.shape[axis]
        reshape = False
    if np.abs(shift) > n:
        res = np.zeros_like(a)
    elif shift < 0:
        shift += n
        zeros = np.zeros_like(a.take(np.arange(n-shift), axis))
        res = np.concatenate((a.take(np.arange(n-shift,n), axis), zeros), axis)
    else:
        zeros = np.zeros_like(a.take(np.arange(n-shift,n), axis))
        res = np.concatenate((zeros, a.take(np.arange(n-shift), axis)), axis)
    if reshape:
        return res.reshape(a.shape)
    else:
        return res

In [ ]:
from scipy.ndimage import zoom

#https://stackoverflow.com/questions/37119071/scipy-rotate-and-zoom-an-image-without-changing-its-dimensions
def clipped_zoom(img, zoom_factor, **kwargs):

    h, w = img.shape

    # For multichannel images we don't want to apply the zoom factor to the RGB
    # dimension, so instead we create a tuple of zoom factors, one per array
    # dimension, with 1's for any trailing dimensions after the width and height.
    zoom_tuple = (zoom_factor,) * 2 + (1,) * (img.ndim - 2)

    # Zooming out
    if zoom_factor < 1:

        # Bounding box of the zoomed-out image within the output array
        zh = int(np.round(h * zoom_factor))
        zw = int(np.round(w * zoom_factor))
        top = (h - zh) // 2
        left = (w - zw) // 2

        # Zero-padding
        out = np.zeros_like(img)
        out[top:top+zh, left:left+zw] = zoom(img, zoom_tuple, order=0)

    # Zooming in
    elif zoom_factor > 1:

        # Bounding box of the zoomed-in region within the input array
        zh = int(np.round(h / zoom_factor))
        zw = int(np.round(w / zoom_factor))
        top = (h - zh) // 2
        left = (w - zw) // 2

        out = zoom(img[top:top+zh, left:left+zw], zoom_tuple, order=0)

        # `out` might still be slightly larger than `img` due to rounding, so
        # trim off any extra pixels at the edges
        #trim_top = ((out.shape[0] - h) // 2)
        #trim_left = ((out.shape[1] - w) // 2)
        #out = out[trim_top:trim_top+h, trim_left:trim_left+w]

        while out.shape[0] < 100:
            out = np.pad(out,((0,1),(0,0)), 'edge')
        while out.shape[1] < 100:
            out = np.pad(out,((0,0),(0,1)), 'edge')
        while out.shape[0] > 100:
            out = out[:100,:]
        while out.shape[1] > 100:
            out = out[:,:100]
            
    return out